# Generated by Django 2.0.6 on 2018-06-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecobrick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='brickNum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='brickWeight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
